import { test } from "vitest";

test("console test", () => {
  // Этот тест проходит, потому что он не выбрасывает исключение.
  console.log("test");
  // sayHello();
});
